### ISSUE TITLE
[Question] Force Simulator to Dark Mode 

### ISSUE THREAD

**Issue by Blackjacx** [ChargePoint/xcparse#32]
Hey there,

first of all thank you for this awesome tool! I read your Blog post about xcparse and saw a bitrise step that forces the simulator to dark mode. I wanted to ask if you could share how this works since this would be a nice addition for us too :-)

(you can of course remove the bug label :-/ )

**Comment by abotkin-cpi** [comment]
So right now, we're cheating to do it.  We use Bitrise for our CI & just have a script step before running xcodebuild where we check an environment variable we set for the test run that contains either "Dark" or "Light" & modify the Info.plist of the app like so:

```
# Set the Info.plist to the style we want
/usr/libexec/PlistBuddy -c 'Add :UIUserInterfaceStyle string "$CHARGEPOINT_UIINTERFACESTYLE"' ChargePoint/Supporting\ Files/CP/CP-Info.plist
```

Back in the early Xcode 11 betas, we were using a launch argument in our test plan run configuration & then on launch of the app, our debug version would compile in code to check the launch arguments & then set the UIWindow's override.

Launch argument: ```-CPTUIUserInterfaceStyle Dark```

Code in `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions `
```
    if (@available(iOS 13, *)) {
        id interfaceStyleOverrideObj = [[NSUserDefaults standardUserDefaults] objectForKey:@"CPTUIUserInterfaceStyle"];
        if (interfaceStyleOverrideObj && [interfaceStyleOverrideObj isKindOfClass:[NSString class]]) {
            NSString *interfaceStyleOverride = (NSString *)interfaceStyleOverrideObj;
            if ([interfaceStyleOverride isEqualToString:@"Light"]) {
                NSLogWarn(@"User interface overide set for Light Mode");
                self.window.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
            } else if ([interfaceStyleOverride isEqualToString:@"Dark"]) {
                NSLogWarn(@"User interface overide set for Dark Mode");
                self.window.overrideUserInterfaceStyle = UIUserInterfaceStyleDark;
            }
        }
    }
```

Unfortunately, that functionality of test run configurations broke starting from Xcode 11 beta 4 and is broken in all GM Xcode 11s (including 11.2.1).  The launch arguments in the test run configurations are not used by default by XCUIApplication launches like it did in Xcode 11 beta 3.

We wrote an example app showing the problem & submitted feedback to Apple when Xcode 11 beta 4 broke it, but it's still open & likely to stay that way as it doesn't seem the screener is running the test project to see the issue as I keep getting "Does it still reproduce?" messages when the test project shows it does.

Feedback Number is FB6797480.  Here are the example project I gave to Apple & instructions to reproduce below for anyone who wants to file similarly with them:

`I'm attaching a project that exhibits the issue.  In the project, if you run the app, you'll see a launch argument was provided in the run step & the launch argument's value is show in the view controller.  If you then try to take advantage of the test plan's launch arguments in TestPlanFail.xctestplan & do a UI test, you'll note that the launch argument defined in the test run is not passed (as shown by the failed test).  The only way to work around this is shown in the test that succeeds where you set the launch arguments on the XCUIApplication directly, but you can't read test run configuration (AFAIK) from within your UI test.`

[TestPlanFail.zip](https://github.com/ChargePoint/xcparse/files/3844034/TestPlanFail.zip)

**Comment by abotkin-cpi** [comment]
@Blackjacx Let me know if this provides enough help.  If so, feel free to close this ticket out.  If there's something you think would be interesting to know more about, let me know & maybe we can get a blog post written up about the topic & how we do it.

**Comment by Blackjacx** [comment]
Wow thanks so much for the explanation! This helps already a lot :-)
