### ISSUE TITLE
xcparse logs does not include logs for App target

### ISSUE THREAD

**Issue by tomasebrennan** [ChargePoint/xcparse#33]
Previously when looking at test failures we were able to view logs for both the Tests target and the app target. So if say we threw an NSLog in our App we could look at our app logs and see if that affected the tests.

Since the move to Xcode 11 and the .xcresult package I haven't been able to find the App logs. This seems to be an issue with xcparse too as when use `xcparse logs` I only get the logs for the Tests target and the build logs.

Have you been able to find how to retrieve the app logs from the .xcresult file? And if so can `xcparse logs` be updated to return this?

**Comment by abotkin-cpi** [comment]
@tomasebrennan Thanks for the report & bringing this up!  I'll add the exporting of the Diagnostics folder that you used to get the logs out of into the logs command as part of xcparse 1.1 & that should contain the host log.  It's pretty straight-forward, so expect sometime mid next week.

In the meanwhile, here's a workaround until xcparse 1.1 is out.  Be warned, it's very manual.  If you run the attachments sub-command in verbose mode, you'll be able to see all the JSON of the various actions that occurred via xcparse.  That command should look something like this:

`xcparse attachments -v ./Test.xcresult ./attachments`

If you search the output, you'll be able to find a "diagnosticsRef" that that has an ID we need for exporting.  It'll look something like this:

```
          "diagnosticsRef" : {
            "_type" : {
              "_name" : "Reference"
            },
            "id" : {
              "_type" : {
                "_name" : "String"
              },
              "_value" : "0~d5MG0zjsord-viE2e0Sxez1rpXje9hTxhORrNYcDuqkWcz6iFRYf7EKJkZcKIV7WYBJRvP4Z98TG5bW4L7hT-Q=="
            }
          },
```

Grab that ID value & run the following command in Terminal (replacing the ID value with what you found above):

`xcrun xcresulttool export --id 0~d5MG0zjsord-viE2e0Sxez1rpXje9hTxhORrNYcDuqkWcz6iFRYf7EKJkZcKIV7WYBJRvP4Z98TG5bW4L7hT-Q== --path ./Test.xcresult --type directory --output-path ./Diagnostics`

**Comment by abotkin-cpi** [comment]
xcparse 2.0.0 now allows for the extraction of the Diagnostics folder with the logs subcommand.

`xcparse logs ./TestResults-iPhoneXRKoreanTestRun.xcresult ./logs`

<img width="1123" alt="screenshots_logs" src="https://user-images.githubusercontent.com/25309848/69268413-ee9b5500-0b83-11ea-9a0f-12a101e2197a.png">

You can update xcparse via:

`brew upgrade xcparse`

Thanks @tomasebrennan for this feature suggestion!
