### ISSUE TITLE
Thanks for the awesome tool

### ISSUE THREAD

**Issue by onmyway133** [ChargePoint/xcparse#39]
Hi, this is not a bug report, just want to say huge thank to this tool ❤️ 
I've started using it in my project, and integrate it in Puma tool https://github.com/pumaswift/Puma/pull/20

**Comment by abotkin-cpi** [comment]
🎉 Thanks @onmyway133! Always happy to hear from folks using the tool and do feel free to open tickets for anything you’d like to see improved, added, etc!

@rsukumar75
